name: solid_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  integration_test:
    sdk: flutter
  shared_preferences: ^2.1.0
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  solid_lints: ^0.0.14
  
flutter: 
  uses-material-design: true
